# Generated by Django 3.1 on 2020-09-04 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_validable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('followed_tags', models.ManyToManyField(blank=True, related_name='User_tags', to='catalog.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kicked_out_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('messages_per_minute', models.IntegerField()),
                ('time_between_messages', models.IntegerField()),
                ('max_users', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administrator', models.ManyToManyField(related_name='Chat_administrators', to='catalog.User_validable')),
                ('banned_users', models.ManyToManyField(blank=True, related_name='Chat_banned', to='catalog.User_validable')),
                ('kicked_out_user', models.ManyToManyField(blank=True, related_name='Chat_kickeds', to='catalog.Kicked_out_user')),
                ('messages', models.ManyToManyField(blank=True, related_name='Chat_messages', to='catalog.Message')),
                ('moderators', models.ManyToManyField(blank=True, related_name='Chat_moderators', to='catalog.User_validable')),
                ('tags', models.ManyToManyField(related_name='Chatroom_tags', to='catalog.Tag')),
                ('users', models.ManyToManyField(blank=True, related_name='Chat_users', to='catalog.User_validable')),
            ],
        ),
    ]
