# Generated by Django 3.1 on 2020-10-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_motivosdenuncias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivosDenuncias',
            new_name='ReportTypes',
        ),
    ]
