# Generated by Django 3.1 on 2020-09-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200925_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kicked_out_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='Kicked_out_user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
