# Generated by Django 3.1 on 2020-09-28 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('messages_per_minute', models.IntegerField()),
                ('time_between_messages', models.IntegerField()),
                ('max_users', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user_validable')),
                ('banned_users', models.ManyToManyField(blank=True, related_name='Chat_banned', to='catalog.User_validable')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='messages_images')),
                ('file', models.FileField(blank=True, upload_to='messages_files')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatRoom.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user_validable')),
            ],
        ),
        migrations.CreateModel(
            name='Kicked_out_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, to='catalog.user_validable')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='kicked_out_user',
            field=models.ManyToManyField(blank=True, related_name='Chat_kickeds', to='chatRoom.Kicked_out_user'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='Chat_moderators', to='catalog.User_validable'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tags',
            field=models.ManyToManyField(related_name='Chatroom_tags', to='catalog.Tag'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Chat_users', to='catalog.User_validable'),
        ),
    ]
