# Generated by Django 3.1 on 2020-10-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('chatRoom', '0004_auto_20200928_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='complaints_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='complaints_users',
            field=models.ManyToManyField(blank=True, related_name='Chat_Usersquedenunciaron', to='catalog.User_validable'),
        ),
    ]
