# Generated by Django 3.1 on 2020-10-13 00:59

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('chatRoom', '0005_auto_20201011_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='complaints_counter',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='complaints_users',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('types', models.ManyToManyField(related_name='Reports_Motives', to='chatRoom.Type_Report')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='catalog.user_validable')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='Chat_reports', to='chatRoom.Report'),
        ),
    ]
