# Generated by Django 3.1 on 2020-10-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_motivosdenuncias'),
        ('chatRoom', '0005_auto_20201011_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='complaints_counter',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='complaints_users',
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('motivos', models.ManyToManyField(related_name='Motivos_Denuncias', to='catalog.MotivosDenuncias')),
            ],
        ),
    ]
