# Generated by Django 3.1 on 2020-10-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0006_auto_20201012_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='types',
            new_name='motives',
        ),
    ]
