# Generated by Django 3.1 on 2020-10-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0007_auto_20201012_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
