# Generated by Django 3.1 on 2020-10-12 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_motivosdenuncias'),
        ('catalog', '0003_auto_20201012_0303'),
        ('chatRoom', '0007_auto_20201011_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reporttypes')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='catalog.user_validable')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='denuncias',
        ),
        migrations.DeleteModel(
            name='Denuncias',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='Chat_reports', to='chatRoom.Reports'),
        ),
    ]
