# Generated by Django 3.1 on 2020-10-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0008_auto_20201012_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
