# Generated by Django 3.1 on 2020-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201012_0303'),
        ('chatRoom', '0009_reports_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='motive',
        ),
        migrations.AddField(
            model_name='reports',
            name='motive',
            field=models.ManyToManyField(related_name='Reports_Motives', to='catalog.ReportTypes'),
        ),
    ]
