# Generated by Django 3.1 on 2020-10-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0009_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kicked_out_user',
            name='time',
        ),
    ]
