# Generated by Django 3.1 on 2020-10-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0010_auto_20201012_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='motive',
            new_name='motives',
        ),
    ]
