# Generated by Django 3.1 on 2020-10-13 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0010_remove_kicked_out_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicked_out_user',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
