# Generated by Django 3.1 on 2020-10-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0011_auto_20201012_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
